"""Offline license system (Personnel / Entreprise).

A print shop may run with no internet, so licenses are validated OFFLINE: a
license is a small JSON payload signed by the vendor with an Ed25519 private
key; the application embeds only the matching PUBLIC key and verifies the
signature. Editing the payload (to grant Enterprise, lift the cap…) breaks the
signature, and forging a new one needs the private key, which never ships.

What the tiers gate (all four axes the client asked for):
- advanced modules (ganging, watch rules, reports, API…) — Enterprise only;
- number of posts — a Personnel license is bound to one machine's fingerprint;
- daily volume — Personnel is capped, Enterprise is unlimited;
- watermark — Personnel stamps a discreet mark on sheets, Enterprise does not.

Without any license the app runs in a restricted "Non activé" mode = the most
limited Personnel behaviour, so it is usable but clearly unlicensed.
"""

import base64
import hashlib
import json
import logging
import sys
from dataclasses import dataclass, field
from datetime import date
from enum import Enum
from pathlib import Path
from typing import List, Optional

logger = logging.getLogger(__name__)

# Vendor public key (Ed25519, base64 of the 32-byte raw key). The matching
# PRIVATE key is generated by scripts/license_admin.py and kept by JELOTIA —
# it must never be committed. Replace this with your own via that script.
PUBLIC_KEY_B64 = "Vdc4HOyK/zebWtK84nU1C38x/+BsD5gC6gb4oHexloE="

# Features gated to Enterprise. Referenced by name so the UI can ask
# license.allows("ganging") without importing anything else.
#
# "multi_post" USED TO BE LISTED HERE and was never checked anywhere — which
# read either as a paid feature given away, or as a dead entry. It was the
# latter: the single-workstation restriction is real but enforced differently,
# by binding a Personnel licence to a machine fingerprint (see parse_license).
# A flag nobody reads only obscures that.
ENTERPRISE_FEATURES = frozenset({"ganging", "watch_rules", "reports", "api"})

# Declared above but not built yet: there is no product API to gate today (it
# is the E1 roadmap item; the activation server is vendor-side infrastructure,
# not a customer feature). Listed explicitly so the gate is not forgotten the
# day it ships — a test asserts every OTHER Enterprise feature is really gated.
UNIMPLEMENTED_FEATURES = frozenset({"api"})

# Restricted defaults when no valid license is present.
UNLICENSED_MAX_FILES_PER_DAY = 50


class LicenseTier(str, Enum):
    PERSONAL = "personal"
    ENTERPRISE = "enterprise"


def _license_dir() -> Path:
    from src.utils.config import config

    return Path(config.base_dir)


def license_file() -> Path:
    return _license_dir() / "license.key"


def bundled_license_file() -> Optional[Path]:
    """A license shipped next to the executable by the installer (OEM / factory
    pre-activation for JELOTIA's internal machines). Only meaningful in a frozen
    build — in that case the installer drops `license.key` beside the .exe so the
    app is activated on first launch with no manual step. A license the user
    activates later (stored via license_file()) always takes precedence."""
    if not getattr(sys, "frozen", False):
        return None
    return Path(sys.executable).parent / "license.key"


def machine_fingerprint() -> str:
    """A stable per-machine id used to bind a Personnel license to one post.

    Windows' MachineGuid is the most stable source (survives reboots, disk
    changes); the hostname + primary MAC are a fallback. Hashed so the raw
    identifiers never appear in the license file.
    """
    parts: List[str] = []
    try:
        import winreg

        key = winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Cryptography"
        )
        parts.append(winreg.QueryValueEx(key, "MachineGuid")[0])
    except Exception:
        import platform
        import uuid

        parts.append(platform.node())
        parts.append(str(uuid.getnode()))
    digest = hashlib.sha256("|".join(parts).encode("utf-8")).hexdigest()
    return digest[:32]


@dataclass
class License:
    tier: LicenseTier
    licensee: str = ""
    machine_id: str = ""          # "" = not machine-bound (Enterprise)
    max_files_per_day: int = 0    # 0 = unlimited
    expires: Optional[date] = None
    features: List[str] = field(default_factory=list)
    valid: bool = True
    reason: str = ""              # why an invalid license is invalid

    # ---- derived checks -------------------------------------------------- #

    @property
    def is_enterprise(self) -> bool:
        return self.valid and self.tier == LicenseTier.ENTERPRISE

    @property
    def unlimited_volume(self) -> bool:
        return self.max_files_per_day <= 0

    def allows(self, feature: str) -> bool:
        """True if this feature is usable under the current license."""
        if not self.valid:
            return feature not in ENTERPRISE_FEATURES
        if feature in ENTERPRISE_FEATURES:
            return self.is_enterprise or feature in self.features
        return True

    @property
    def watermark(self) -> bool:
        """Personnel and unlicensed stamp a mark; Enterprise does not."""
        return not self.is_enterprise

    @property
    def label(self) -> str:
        if not self.valid:
            return "Non activé"
        return "Entreprise" if self.is_enterprise else "Personnel"


def unlicensed(reason: str = "Aucune licence") -> License:
    """The restricted mode used when no valid license is present."""
    return License(
        tier=LicenseTier.PERSONAL,
        max_files_per_day=UNLICENSED_MAX_FILES_PER_DAY,
        valid=False,
        reason=reason,
    )


# --------------------------------------------------------------------------- #
#  Signing / verification                                                     #
# --------------------------------------------------------------------------- #

def _canonical_payload(data: dict) -> bytes:
    """Deterministic bytes to sign/verify: the payload without its signature,
    keys sorted, compact — so re-serialisation always matches."""
    body = {k: v for k, v in data.items() if k != "sig"}
    return json.dumps(body, sort_keys=True, separators=(",", ":")).encode("utf-8")


def sign_payload(payload: dict, private_key_b64: str) -> str:
    """Vendor side (license_admin.py): returns the base64 Ed25519 signature of
    the canonical payload."""
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

    raw = base64.b64decode(private_key_b64)
    key = Ed25519PrivateKey.from_private_bytes(raw)
    signature = key.sign(_canonical_payload(payload))
    return base64.b64encode(signature).decode("ascii")


def build_signed_license(
    private_key_b64: str,
    tier: str,
    licensee: str = "",
    machine_id: str = "",
    max_files_per_day: int = 0,
    expires: str = "",
    features: Optional[List[str]] = None,
    issued: Optional[str] = None,
) -> str:
    """Vendor side: build a license payload, sign it, and return the base64
    license key a customer installs. Single source of truth for the payload
    shape — shared by scripts/license_admin.py and the activation server, so the
    two can never drift from what parse_license() expects."""
    payload = {
        "tier": tier,
        "licensee": licensee,
        "machine_id": machine_id or "",
        "max_files_per_day": int(max_files_per_day or 0),
        "expires": expires or "",
        "features": list(features or []),
        "issued": issued or date.today().isoformat(),
    }
    payload["sig"] = sign_payload(payload, private_key_b64)
    return base64.b64encode(
        json.dumps(payload, separators=(",", ":")).encode("utf-8")
    ).decode("ascii")


def _verify_signature(data: dict, public_key_b64: str) -> bool:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

    try:
        key = Ed25519PublicKey.from_public_bytes(base64.b64decode(public_key_b64))
        key.verify(base64.b64decode(data["sig"]), _canonical_payload(data))
        return True
    except Exception:
        # Any failure — bad signature, malformed key, missing "sig" — means
        # "not authentic". Verification must never raise.
        return False


def parse_license(
    key_text: str,
    public_key_b64: Optional[str] = None,
    fingerprint: Optional[str] = None,
    today: Optional[date] = None,
) -> License:
    """Turns license text into a License, verifying signature, machine binding
    and expiry. Always returns a License — an invalid one carries `reason`."""
    public_key_b64 = public_key_b64 or PUBLIC_KEY_B64
    today = today or date.today()

    try:
        data = json.loads(base64.b64decode(key_text.strip()).decode("utf-8"))
    except Exception:
        try:
            data = json.loads(key_text)
        except Exception:
            return unlicensed("Clé de licence illisible")

    if not _verify_signature(data, public_key_b64):
        return unlicensed("Signature invalide — licence non authentique")

    try:
        tier = LicenseTier(data["tier"])
    except (KeyError, ValueError):
        return unlicensed("Type de licence inconnu")

    expires = None
    if data.get("expires"):
        try:
            expires = date.fromisoformat(data["expires"])
        except ValueError:
            return unlicensed("Date d'expiration illisible")
        if expires < today:
            return unlicensed(f"Licence expirée le {expires:%d/%m/%Y}")

    machine_id = data.get("machine_id", "") or ""
    if machine_id:
        fp = fingerprint or machine_fingerprint()
        if machine_id != fp:
            return unlicensed("Licence liée à un autre poste")

    return License(
        tier=tier,
        licensee=data.get("licensee", ""),
        machine_id=machine_id,
        max_files_per_day=int(data.get("max_files_per_day", 0) or 0),
        expires=expires,
        features=list(data.get("features", [])),
        valid=True,
    )


# --------------------------------------------------------------------------- #
#  App-side accessor                                                          #
# --------------------------------------------------------------------------- #

_cached: Optional[License] = None


def current_license(refresh: bool = False) -> License:
    """The active license, read once and cached. Resolution order:

    1. a license the user activated in F7 (license_file(), in the data folder);
    2. the OEM license the installer bundled next to the exe (bundled_license_file()).

    The user copy wins so an operator can always upgrade a pre-installed machine.
    Missing or invalid on both → restricted unlicensed mode.
    """
    global _cached
    if _cached is not None and not refresh:
        return _cached

    first_invalid: Optional[License] = None
    for path in (license_file(), bundled_license_file()):
        if path is None or not path.exists():
            continue
        try:
            lic = parse_license(path.read_text(encoding="utf-8"))
        except OSError as e:
            lic = unlicensed(f"Licence illisible : {e}")
        if lic.valid:
            _cached = lic
            return _cached
        first_invalid = first_invalid or lic

    _cached = first_invalid or unlicensed("Aucune licence installée")
    return _cached


def install_license(key_text: str) -> License:
    """Validates then stores a license; the parsed result is returned so the
    caller can show the tier or the failure reason."""
    parsed = parse_license(key_text)
    if not parsed.valid:
        return parsed
    path = license_file()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(key_text.strip(), encoding="utf-8")
    global _cached
    _cached = parsed
    return parsed
